### PR TITLE
Updates on .NET

### PR DESCRIPTION
**Pull request by peterpogorski**

### CODE REVIEW

**Review by jeffj6123 — APPROVED** [review]

**Comment by juho-hanhimaki** [comment]
What does the lack of support for .NET (core) version X apps actually mean?

I have been testing / running .NET 5 RC apps on clusters with no visible issues.  Are there some compatibility issues that should be expected when running apps on "unsupported" .NET runtime version?

**Comment by peterpogorski** [comment]
@juho-hanhimaki - That is correct, there some compatibility issues introduced by the internal tooling we use to create the SF packages. We are working to remove these issues so that we can ensure that we have full compatibility in the 8.0 release.

**Comment by juho-hanhimaki** [comment]
Would be useful to have more specific information. Will my .NET 5 stateful service crash and explode some day on it's own even though it currently runs perfectly fine? Or is it purely tooling related stuff which is not expected to cause runtime issues on a working service.

**Comment by LeroyK** [comment]
@peterpogorski can you elaborate on what these issues are?

**Pull request merged**
