### PR TITLE
Handle *.png as binary in .gitattributes

### PR DESCRIPTION
**Pull request by spaletta**
PNGs (some) contain bare CR bytes, and will be both corrupted and perpetually viewed as changed by git.

### CODE REVIEW

**Comment by spaletta** [comment]
@samedder well, sure, but there is a generous "* text" line in the .gitattributes in this project.

**Comment by samedder** [comment]
@spaletta do you have an example of where we have a PNG committed?

**Comment by spaletta** [comment]
@samedder:

    $ git ls-tree -r --name-only upstream/master | grep '\.png$'
    docs/architecture/Images/APIs_E.png
    docs/architecture/Images/Application_E.png
    docs/architecture/Images/Communication_E.png
    docs/architecture/Images/Federation_E.png
    docs/architecture/Images/Hosting_E.png
    docs/architecture/Images/Management_E.png
    docs/architecture/Images/Reliability_E.png
    docs/architecture/Images/Testability_E.png
    docs/architecture/Images/Transport_E.png
    docs/architecture/Images/UserApps_E.png
    $

**Comment by samedder** [comment]
@spaletta thanks for bringing this up, I wasn't aware. I'll take a look at all the extensions we have and make more changes to make sure they're treated as binary when necessary.

**Pull request merged**
